name: PigAPI
main: com.xzzpig.bukkit.pigapi.plugin.Main
version: V1.0
author: xzzpig
commands:
  pigapi:
    description: PigAPI的主命令
    usage: /pigapi help
permission:
  pigapi.command.reloadscript: 
    description: /pigapi reloadscript权限
    default: op
  pigapi.command.runscript: 
    description: /pigapi runscript权限
    default: op
    